# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-06-21 11:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genres',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Tracks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('track_name', models.CharField(max_length=100)),
                ('genre', models.CharField(max_length=50, null=True)),
                ('artist', models.CharField(blank=True, default='', max_length=100)),
                ('release_year', models.IntegerField(null=True)),
                ('rating', models.IntegerField(null=True)),
            ],
        ),
    ]
