# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-06-21 12:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TrackLister', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tracks',
            name='artist',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='tracks',
            name='genre',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='tracks',
            name='rating',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tracks',
            name='release_year',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
