# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-06-21 13:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TrackLister', '0003_auto_20160621_1251'),
    ]

    operations = [
        migrations.AddField(
            model_name='tracks',
            name='ablum',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
