# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-06-23 09:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TrackLister', '0004_tracks_ablum'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tracks',
            old_name='ablum',
            new_name='album',
        ),
    ]
